In [3]:
import pandas as pd
import numpy as np
import sklearn.metrics as sk
from sklearn.metrics.pairwise import cosine_similarity

In [4]:
data = [[1.5,1.7],[2,1.9], [1.6,1.8], [1.2,1.5],[1.5,1]]

df = pd.DataFrame(data, columns=['A1', 'A2'])

print(df)


    A1   A2
0  1.5  1.7
1  2.0  1.9
2  1.6  1.8
3  1.2  1.5
4  1.5  1.0


In [5]:
x=np.array([
    [1.5,1.7], #x1 
    [2,1.9], #x2
    [1.6,1.8], #x3
    [1.2,1.5], #x4
    [1.5,1] #x5
])

y = np.array([[1.4,1.6]])

print(y)

[[1.4 1.6]]


In [6]:
print("Pairwise")
pair = sk.pairwise_distances(x, y, metric="cosine")
print(pair)
print('')
print("CosineSimilarity")
cosine_similarity(x,y)


Pairwise
[[8.60855604e-06]
 [4.24773875e-03]
 [3.05161812e-05]
 [9.71765062e-04]
 [3.46366070e-02]]

CosineSimilarity


array([[0.99999139],
       [0.99575226],
       [0.99996948],
       [0.99902823],
       [0.96536339]])

In [7]:
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity

# Given data
data = [[1.5, 1.7], [2, 1.9], [1.6, 1.8], [1.2, 1.5], [1.5, 1]]
df = pd.DataFrame(data, columns=['A1', 'A2'])

# Query point
query_point = [[1.4, 1.6]]

# Calculate cosine similarity using sklearn.metrics.pairwise.cosine_similarity
cosine_similarities = cosine_similarity(df, query_point)

# Convert the result to a pandas DataFrame for better display
cosine_sim_df = pd.DataFrame(cosine_similarities, index=df.index, columns=['Cosine Similarity'])

# Rank the database points based on similarity with the query
ranked_points = cosine_sim_df.sort_values(by='Cosine Similarity', ascending=False)

# Display the ranked points
print("Cosine Similarity Rankings:")
print(ranked_points)

Cosine Similarity Rankings:
   Cosine Similarity
0           0.999991
2           0.999969
3           0.999028
1           0.995752
4           0.965363
