# **Homework 2**
## **Author: Jake Brulato**

**Import the Packages**

In [77]:
import pandas as pd
from sklearn.decomposition import PCA
import numpy as np
import matplotlib.pyplot as plt
import seaborn as snspi 

**Read the data**

In [78]:
data = pd.read_table('Nichols_Nicki.dat')
data

ias1  ias2  ias3  ias4  ias5  ias6  ias7  ias8  ias9  ias10  ...  ias27  \
0       1     1     2     1     1     1     1     2     2      1  ...      3   
1       2     1     3     1     2     1     1     2     1      1  ...      3   
2       4     2     4     2     3     3     4     2     3      3  ...      3   
3       1     1     3     1     1     1     1     2     1      1  ...      1   
4       2     1     3     2     1     1     1     2     3      1  ...      3   
..    ...   ...   ...   ...   ...   ...   ...   ...   ...    ...  ...    ...   
202     1     1     3     2     2     1     1     2     1      1  ...      3   
203     1     1     4     1     1     1     1     3     1      1  ...      2   
204     3     2     4     3     2     3     2     4     4      2  ...      2   
205     3     1     5     1     1     3     4     3     2      2  ...      4   
206     1     1     1     1     2     1     3     4     4      3  ...      2   

     ias28  ias29  ias30  ias31  ias32  ias33  ias34  ias35  ias36  
0        1      1      1      1      1      1      1      1      1  
1        1      1      1      2      1      2      1      1      1  
2        2      2      3      3      1      2      2      1      3  
3        1      1      1      2      1      1      1      1      1  
4        1      1      1      2      1      1      1      3      1  
..     ...    ...    ...    ...    ...    ...    ...    ...    ...  
202      1      1      3      4      3      1      1      1      1  
203      1      1      1      2      1      1      1      2      1  
204      2      1      4      2      4      2      1      1      1  
205      3      1      1      4      3      1      1      1      1  
206      3      2      2      2      3      1      1      2      3  

[207 rows x 36 columns]

**Successfully remove the two variables with low variances**

In [79]:
stats = data.describe().T.sort_values("std").head()
print(stats)

       count      mean       std  min  25%  50%  75%  max
ias34  207.0  1.111111  0.344474  1.0  1.0  1.0  1.0  3.0
ias23  207.0  1.144928  0.427525  1.0  1.0  1.0  1.0  3.0
ias15  207.0  1.231884  0.516098  1.0  1.0  1.0  1.0  3.0
ias28  207.0  1.236715  0.563454  1.0  1.0  1.0  1.0  4.0
ias6   207.0  1.222222  0.565075  1.0  1.0  1.0  1.0  4.0


**Alternative way to remove the two variables with low variances**

In [80]:
variances = data.var()
lowest_variance_items = variances.nsmallest(2).index.tolist()
print("Items dropped for low variances:", lowest_variance_items)
var_drop = data.drop(['ias34','ias23'], axis= 1)
var_drop

Items dropped for low variances: ['ias34', 'ias23']


ias1  ias2  ias3  ias4  ias5  ias6  ias7  ias8  ias9  ias10  ...  ias26  \
0       1     1     2     1     1     1     1     2     2      1  ...      1   
1       2     1     3     1     2     1     1     2     1      1  ...      1   
2       4     2     4     2     3     3     4     2     3      3  ...      3   
3       1     1     3     1     1     1     1     2     1      1  ...      1   
4       2     1     3     2     1     1     1     2     3      1  ...      1   
..    ...   ...   ...   ...   ...   ...   ...   ...   ...    ...  ...    ...   
202     1     1     3     2     2     1     1     2     1      1  ...      1   
203     1     1     4     1     1     1     1     3     1      1  ...      1   
204     3     2     4     3     2     3     2     4     4      2  ...      3   
205     3     1     5     1     1     3     4     3     2      2  ...      2   
206     1     1     1     1     2     1     3     4     4      3  ...      1   

     ias27  ias28  ias29  ias30  ias31  ias32  ias33  ias35  ias36  
0        3      1      1      1      1      1      1      1      1  
1        3      1      1      1      2      1      2      1      1  
2        3      2      2      3      3      1      2      1      3  
3        1      1      1      1      2      1      1      1      1  
4        3      1      1      1      2      1      1      3      1  
..     ...    ...    ...    ...    ...    ...    ...    ...    ...  
202      3      1      1      3      4      3      1      1      1  
203      2      1      1      1      2      1      1      2      1  
204      2      2      1      4      2      4      2      1      1  
205      4      3      1      1      4      3      1      1      1  
206      2      3      2      2      2      3      1      2      3  

[207 rows x 34 columns]

In [81]:
var_drop.corr()

ias1      ias2      ias3      ias4      ias5      ias6      ias7  \
ias1   1.000000  0.427736  0.462768  0.354683  0.517041  0.558645  0.478892   
ias2   0.427736  1.000000  0.330520  0.541461  0.379329  0.239192  0.394668   
ias3   0.462768  0.330520  1.000000  0.518899  0.474619  0.405834  0.485200   
ias4   0.354683  0.541461  0.518899  1.000000  0.462147  0.266996  0.451263   
ias5   0.517041  0.379329  0.474619  0.462147  1.000000  0.481312  0.429718   
ias6   0.558645  0.239192  0.405834  0.266996  0.481312  1.000000  0.497405   
ias7   0.478892  0.394668  0.485200  0.451263  0.429718  0.497405  1.000000   
ias8   0.476363  0.316346  0.624529  0.444075  0.588049  0.433835  0.465954   
ias9   0.512624  0.285332  0.500271  0.369303  0.508687  0.499149  0.541858   
ias10  0.431542  0.295806  0.401046  0.370661  0.520405  0.587692  0.601882   
ias11  0.418803  0.260113  0.428615  0.266908  0.336068  0.420593  0.407984   
ias12  0.426479  0.317615  0.456818  0.441042  0.437743  0.502373  0.601532   
ias13  0.124036  0.372073  0.194782  0.306512  0.237406  0.103051  0.222779   
ias14  0.491962  0.379893  0.397842  0.358068  0.401625  0.438143  0.370700   
ias15  0.509146  0.351126  0.423629  0.265769  0.371215  0.388393  0.358756   
ias16  0.515407  0.304038  0.402412  0.306861  0.356878  0.386070  0.269290   
ias17  0.350424  0.251870  0.385572  0.287606  0.403659  0.501472  0.497956   
ias18  0.469139  0.277870  0.358034  0.338143  0.467455  0.385915  0.550950   
ias19  0.464207  0.280455  0.651083  0.424867  0.510969  0.493863  0.436590   
ias20  0.484599  0.293493  0.444332  0.416140  0.465990  0.445903  0.531041   
ias21  0.468674  0.294715  0.448443  0.359000  0.516034  0.485460  0.550832   
ias22  0.158137  0.145824  0.176206  0.146355  0.151561  0.162702  0.146782   
ias24  0.416092  0.309955  0.599004  0.407175  0.491484  0.383986  0.492671   
ias25  0.454009  0.257624  0.350893  0.370450  0.474929  0.358818  0.394313   
ias26  0.520175  0.284461  0.440439  0.273065  0.432891  0.645433  0.441219   
ias27  0.397178  0.287707  0.390915  0.258987  0.348148  0.325130  0.368297   
ias28  0.492634  0.195700  0.366488  0.219217  0.385675  0.565812  0.421132   
ias29  0.540865  0.324781  0.398712  0.425301  0.554956  0.462595  0.480307   
ias30  0.473830  0.303772  0.417714  0.393186  0.471142  0.423761  0.409551   
ias31  0.325764  0.240185  0.514334  0.276573  0.331626  0.280543  0.326567   
ias32  0.222556  0.149004  0.259528  0.173678  0.250465  0.357838  0.141842   
ias33  0.499462  0.362779  0.449447  0.471634  0.602522  0.353481  0.497770   
ias35  0.380204  0.265065  0.425957  0.250178  0.420797  0.264406  0.250955   
ias36  0.485681  0.317826  0.461002  0.350016  0.469125  0.511114  0.660880   

           ias8      ias9     ias10  ...     ias26     ias27     ias28  \
ias1   0.476363  0.512624  0.431542  ...  0.520175  0.397178  0.492634   
ias2   0.316346  0.285332  0.295806  ...  0.284461  0.287707  0.195700   
ias3   0.624529  0.500271  0.401046  ...  0.440439  0.390915  0.366488   
ias4   0.444075  0.369303  0.370661  ...  0.273065  0.258987  0.219217   
ias5   0.588049  0.508687  0.520405  ...  0.432891  0.348148  0.385675   
ias6   0.433835  0.499149  0.587692  ...  0.645433  0.325130  0.565812   
ias7   0.465954  0.541858  0.601882  ...  0.441219  0.368297  0.421132   
ias8   1.000000  0.630128  0.479893  ...  0.473832  0.400799  0.494156   
ias9   0.630128  1.000000  0.555241  ...  0.458150  0.343674  0.500715   
ias10  0.479893  0.555241  1.000000  ...  0.513612  0.282541  0.476943   
ias11  0.434744  0.439885  0.513844  ...  0.572437  0.359785  0.576448   
ias12  0.540750  0.487878  0.636484  ...  0.534139  0.272353  0.472484   
ias13  0.235583  0.210040  0.208713  ...  0.139385  0.178988  0.187124   
ias14  0.420761  0.448731  0.494793  ...  0.533501  0.399868  0.506398   
ias15  0.423555  0.454797  0.444358  ...  0.648834  0.405559  0.711764   
ias16  0.418536  0.343217  0.249636  ...  0.488769  0.360135 

**Look at the confusion matrix and remove the three variables with low correlations**

In [82]:
corr = var_drop.corr()

# # # If you want to see the matrix in a csv, uncomment below
# conf_df = pd.DataFrame(corr)
# conf_df.to_csv('confusion_matrix.csv', index=True, header=False)

f_data = var_drop.drop(['ias13', 'ias22', 'ias32'], axis=1)
f_data.corr()

ias1      ias2      ias3      ias4      ias5      ias6      ias7  \
ias1   1.000000  0.427736  0.462768  0.354683  0.517041  0.558645  0.478892   
ias2   0.427736  1.000000  0.330520  0.541461  0.379329  0.239192  0.394668   
ias3   0.462768  0.330520  1.000000  0.518899  0.474619  0.405834  0.485200   
ias4   0.354683  0.541461  0.518899  1.000000  0.462147  0.266996  0.451263   
ias5   0.517041  0.379329  0.474619  0.462147  1.000000  0.481312  0.429718   
ias6   0.558645  0.239192  0.405834  0.266996  0.481312  1.000000  0.497405   
ias7   0.478892  0.394668  0.485200  0.451263  0.429718  0.497405  1.000000   
ias8   0.476363  0.316346  0.624529  0.444075  0.588049  0.433835  0.465954   
ias9   0.512624  0.285332  0.500271  0.369303  0.508687  0.499149  0.541858   
ias10  0.431542  0.295806  0.401046  0.370661  0.520405  0.587692  0.601882   
ias11  0.418803  0.260113  0.428615  0.266908  0.336068  0.420593  0.407984   
ias12  0.426479  0.317615  0.456818  0.441042  0.437743  0.502373  0.601532   
ias14  0.491962  0.379893  0.397842  0.358068  0.401625  0.438143  0.370700   
ias15  0.509146  0.351126  0.423629  0.265769  0.371215  0.388393  0.358756   
ias16  0.515407  0.304038  0.402412  0.306861  0.356878  0.386070  0.269290   
ias17  0.350424  0.251870  0.385572  0.287606  0.403659  0.501472  0.497956   
ias18  0.469139  0.277870  0.358034  0.338143  0.467455  0.385915  0.550950   
ias19  0.464207  0.280455  0.651083  0.424867  0.510969  0.493863  0.436590   
ias20  0.484599  0.293493  0.444332  0.416140  0.465990  0.445903  0.531041   
ias21  0.468674  0.294715  0.448443  0.359000  0.516034  0.485460  0.550832   
ias24  0.416092  0.309955  0.599004  0.407175  0.491484  0.383986  0.492671   
ias25  0.454009  0.257624  0.350893  0.370450  0.474929  0.358818  0.394313   
ias26  0.520175  0.284461  0.440439  0.273065  0.432891  0.645433  0.441219   
ias27  0.397178  0.287707  0.390915  0.258987  0.348148  0.325130  0.368297   
ias28  0.492634  0.195700  0.366488  0.219217  0.385675  0.565812  0.421132   
ias29  0.540865  0.324781  0.398712  0.425301  0.554956  0.462595  0.480307   
ias30  0.473830  0.303772  0.417714  0.393186  0.471142  0.423761  0.409551   
ias31  0.325764  0.240185  0.514334  0.276573  0.331626  0.280543  0.326567   
ias33  0.499462  0.362779  0.449447  0.471634  0.602522  0.353481  0.497770   
ias35  0.380204  0.265065  0.425957  0.250178  0.420797  0.264406  0.250955   
ias36  0.485681  0.317826  0.461002  0.350016  0.469125  0.511114  0.660880   

           ias8      ias9     ias10  ...     ias25     ias26     ias27  \
ias1   0.476363  0.512624  0.431542  ...  0.454009  0.520175  0.397178   
ias2   0.316346  0.285332  0.295806  ...  0.257624  0.284461  0.287707   
ias3   0.624529  0.500271  0.401046  ...  0.350893  0.440439  0.390915   
ias4   0.444075  0.369303  0.370661  ...  0.370450  0.273065  0.258987   
ias5   0.588049  0.508687  0.520405  ...  0.474929  0.432891  0.348148   
ias6   0.433835  0.499149  0.587692  ...  0.358818  0.645433  0.325130   
ias7   0.465954  0.541858  0.601882  ...  0.394313  0.441219  0.368297   
ias8   1.000000  0.630128  0.479893  ...  0.507678  0.473832  0.400799   
ias9   0.630128  1.000000  0.555241  ...  0.405041  0.458150  0.343674   
ias10  0.479893  0.555241  1.000000  ...  0.402750  0.513612  0.282541   
ias11  0.434744  0.439885  0.513844  ...  0.418735  0.572437  0.359785   
ias12  0.540750  0.487878  0.636484  ...  0.434414  0.534139  0.272353   
ias14  0.420761  0.448731  0.494793  ...  0.351197  0.533501  0.399868   
ias15  0.423555  0.454797  0.444358  ...  0.395814  0.648834  0.405559   
ias16  0.418536  0.343217  0.249636  ...  0.349604  0.488769  0.360135   
ias17  0.427456  0.501846  0.574666  ...  0.356643  0.542254  0.167287   
ias18  0.459914  0.537954  0.576260  ...  0.522337  0.513394  0.241011   
ias19  0.633020  0.484445  0.490328  ...  0.481793  0.598200  0.383809   
ias20  0.530823  0.516395  0.558987  ...  0.578917  0.622135  0.338626   
ia

**Correct the eigenvalues**

In [83]:
#Calculating the eigen value
# f_cor = f_data.corr()
cov_mat = np.cov(f_data.T)
#np.cov(f_data)

eigen_vals, eigen_vecs = np.linalg.eig(cov_mat)
eigen_vals

array([9.39125543, 1.24515555, 1.10299324, 0.95304005, 0.77301975,
       0.63877591, 0.57708496, 0.53989026, 0.46848507, 0.44204512,
       0.41070427, 0.37201006, 0.36019535, 0.0453143 , 0.05559301,
       0.06549541, 0.32573639, 0.08833419, 0.10109319, 0.30962996,
       0.12344991, 0.13704314, 0.28016405, 0.16390667, 0.16615511,
       0.18382076, 0.19611993, 0.25722439, 0.24472739, 0.22869559,
       0.23002373])

**PCA with all n_components**

In [84]:
pca = PCA(n_components=None)
f_data_pca = pca.fit_transform(f_data)
pca.explained_variance_ratio_

array([0.4586205 , 0.06080698, 0.0538645 , 0.04654156, 0.0377503 ,
       0.03119452, 0.02818185, 0.02636546, 0.0228784 , 0.0215872 ,
       0.02005668, 0.01816705, 0.01759008, 0.01590729, 0.01512073,
       0.01368177, 0.01256151, 0.01195122, 0.01123317, 0.01116831,
       0.00957749, 0.00897686, 0.00811416, 0.00800436, 0.00669248,
       0.00602866, 0.00493687, 0.00431379, 0.00319846, 0.00271488,
       0.00221292])

**PCA with 5 n_components**

In [85]:
pca_5 = PCA(n_components=5)
f_data_pca2 = pca_5.fit_transform(f_data)
pca_5.explained_variance_ratio_

array([0.4586205 , 0.06080698, 0.0538645 , 0.04654156, 0.0377503 ])