In [2]:
import pandas as pd
from sklearn.decomposition import PCA
import numpy as np
import matplotlib.pyplot as plt
import seaborn as snspi 

In [3]:
data = pd.read_table('Nichols_Nicki.dat')
data

ias1  ias2  ias3  ias4  ias5  ias6  ias7  ias8  ias9  ias10  ...  ias27  \
0       1     1     2     1     1     1     1     2     2      1  ...      3   
1       2     1     3     1     2     1     1     2     1      1  ...      3   
2       4     2     4     2     3     3     4     2     3      3  ...      3   
3       1     1     3     1     1     1     1     2     1      1  ...      1   
4       2     1     3     2     1     1     1     2     3      1  ...      3   
..    ...   ...   ...   ...   ...   ...   ...   ...   ...    ...  ...    ...   
202     1     1     3     2     2     1     1     2     1      1  ...      3   
203     1     1     4     1     1     1     1     3     1      1  ...      2   
204     3     2     4     3     2     3     2     4     4      2  ...      2   
205     3     1     5     1     1     3     4     3     2      2  ...      4   
206     1     1     1     1     2     1     3     4     4      3  ...      2   

     ias28  ias29  ias30  ias31  ias32  ias33  ias34  ias35  ias36  
0        1      1      1      1      1      1      1      1      1  
1        1      1      1      2      1      2      1      1      1  
2        2      2      3      3      1      2      2      1      3  
3        1      1      1      2      1      1      1      1      1  
4        1      1      1      2      1      1      1      3      1  
..     ...    ...    ...    ...    ...    ...    ...    ...    ...  
202      1      1      3      4      3      1      1      1      1  
203      1      1      1      2      1      1      1      2      1  
204      2      1      4      2      4      2      1      1      1  
205      3      1      1      4      3      1      1      1      1  
206      3      2      2      2      3      1      1      2      3  

[207 rows x 36 columns]

In [8]:
data.describe().T.sort_values("std").head()
data2 = data.drop(['ias34','ias23'], axis=1)

In [16]:
cov_mat = np.cov(data2.T)
cov_mat

# conf_df = pd.DataFrame(cov_mat)
# conf_df.to_csv('hcm.csv', index=False, header=False)

data3 = data2.drop(['ias13', 'ias22', 'ias31'],axis=1)
data3

ias1  ias2  ias3  ias4  ias5  ias6  ias7  ias8  ias9  ias10  ...  ias25  \
0       1     1     2     1     1     1     1     2     2      1  ...      1   
1       2     1     3     1     2     1     1     2     1      1  ...      1   
2       4     2     4     2     3     3     4     2     3      3  ...      2   
3       1     1     3     1     1     1     1     2     1      1  ...      1   
4       2     1     3     2     1     1     1     2     3      1  ...      1   
..    ...   ...   ...   ...   ...   ...   ...   ...   ...    ...  ...    ...   
202     1     1     3     2     2     1     1     2     1      1  ...      2   
203     1     1     4     1     1     1     1     3     1      1  ...      1   
204     3     2     4     3     2     3     2     4     4      2  ...      2   
205     3     1     5     1     1     3     4     3     2      2  ...      1   
206     1     1     1     1     2     1     3     4     4      3  ...      3   

     ias26  ias27  ias28  ias29  ias30  ias32  ias33  ias35  ias36  
0        1      3      1      1      1      1      1      1      1  
1        1      3      1      1      1      1      2      1      1  
2        3      3      2      2      3      1      2      1      3  
3        1      1      1      1      1      1      1      1      1  
4        1      3      1      1      1      1      1      3      1  
..     ...    ...    ...    ...    ...    ...    ...    ...    ...  
202      1      3      1      1      3      3      1      1      1  
203      1      2      1      1      1      1      1      2      1  
204      3      2      2      1      4      4      2      1      1  
205      2      4      3      1      1      3      1      1      1  
206      1      2      3      2      2      3      1      2      3  

[207 rows x 31 columns]

In [19]:
cov_mat2 = np.cov(data3.T)
cov_mat2

eigen_vals, eigen_vecs = np.linalg.eig(cov_mat2)
eigen_vals

array([9.18654212, 1.16436123, 1.07242556, 0.89444069, 0.81552364,
       0.63704645, 0.58711989, 0.53085178, 0.51437343, 0.45132977,
       0.41177435, 0.40085784, 0.35951261, 0.04355336, 0.05556567,
       0.06627021, 0.08697956, 0.10100122, 0.12158502, 0.3217472 ,
       0.30965643, 0.14106144, 0.27811208, 0.16017261, 0.16551389,
       0.18086815, 0.19457101, 0.25527335, 0.24530609, 0.22771225,
       0.22952852])

In [20]:
pca = PCA(n_components=None)
f_data_pca = pca.fit_transform(data3)
pca.explained_variance_ratio_

array([0.45453995, 0.05761131, 0.05306243, 0.04425594, 0.04035121,
       0.03152035, 0.02905004, 0.02626596, 0.02545063, 0.0223313 ,
       0.02037414, 0.019834  , 0.01778829, 0.0159197 , 0.01532146,
       0.01376068, 0.01263064, 0.01213747, 0.01135682, 0.01126695,
       0.00962716, 0.00894916, 0.00818944, 0.00792516, 0.00697956,
       0.00601589, 0.00499743, 0.00430365, 0.00327898, 0.00274933,
       0.00215497])

In [22]:
pca_5 = PCA(n_components=5)
raq_pca2 = pca_5.fit_transform(data3)
pca_5.explained_variance_ratio_

array([0.45453995, 0.05761131, 0.05306243, 0.04425594, 0.04035121])