In [16]:
import pandas as pd
from sklearn.decomposition import PCA
import numpy as np
import matplotlib.pyplot as plt
import seaborn as snspi 

In [17]:
data = pd.read_table('Nichols_Nicki.dat')
data

ias1  ias2  ias3  ias4  ias5  ias6  ias7  ias8  ias9  ias10  ...  ias27  \
0       1     1     2     1     1     1     1     2     2      1  ...      3   
1       2     1     3     1     2     1     1     2     1      1  ...      3   
2       4     2     4     2     3     3     4     2     3      3  ...      3   
3       1     1     3     1     1     1     1     2     1      1  ...      1   
4       2     1     3     2     1     1     1     2     3      1  ...      3   
..    ...   ...   ...   ...   ...   ...   ...   ...   ...    ...  ...    ...   
202     1     1     3     2     2     1     1     2     1      1  ...      3   
203     1     1     4     1     1     1     1     3     1      1  ...      2   
204     3     2     4     3     2     3     2     4     4      2  ...      2   
205     3     1     5     1     1     3     4     3     2      2  ...      4   
206     1     1     1     1     2     1     3     4     4      3  ...      2   

     ias28  ias29  ias30  ias31  ias32  ias33  ias34  ias35  ias36  
0        1      1      1      1      1      1      1      1      1  
1        1      1      1      2      1      2      1      1      1  
2        2      2      3      3      1      2      2      1      3  
3        1      1      1      2      1      1      1      1      1  
4        1      1      1      2      1      1      1      3      1  
..     ...    ...    ...    ...    ...    ...    ...    ...    ...  
202      1      1      3      4      3      1      1      1      1  
203      1      1      1      2      1      1      1      2      1  
204      2      1      4      2      4      2      1      1      1  
205      3      1      1      4      3      1      1      1      1  
206      3      2      2      2      3      1      1      2      3  

[207 rows x 36 columns]

In [18]:
stats= data.describe().T.sort_values("std").head()
print(stats)
data2 = data.drop(['ias34','ias23'], axis=1)
print(data2)

       count      mean       std  min  25%  50%  75%  max
ias34  207.0  1.111111  0.344474  1.0  1.0  1.0  1.0  3.0
ias23  207.0  1.144928  0.427525  1.0  1.0  1.0  1.0  3.0
ias15  207.0  1.231884  0.516098  1.0  1.0  1.0  1.0  3.0
ias28  207.0  1.236715  0.563454  1.0  1.0  1.0  1.0  4.0
ias6   207.0  1.222222  0.565075  1.0  1.0  1.0  1.0  4.0
     ias1  ias2  ias3  ias4  ias5  ias6  ias7  ias8  ias9  ias10  ...  ias26  \
0       1     1     2     1     1     1     1     2     2      1  ...      1   
1       2     1     3     1     2     1     1     2     1      1  ...      1   
2       4     2     4     2     3     3     4     2     3      3  ...      3   
3       1     1     3     1     1     1     1     2     1      1  ...      1   
4       2     1     3     2     1     1     1     2     3      1  ...      1   
..    ...   ...   ...   ...   ...   ...   ...   ...   ...    ...  ...    ...   
202     1     1     3     2     2     1     1     2     1      1  ...      1   
203     1   

In [19]:
cov_mat = np.cov(data2.T)
print(cov_mat)

# conf_df = pd.DataFrame(cov_mat)
# conf_df.to_csv('hcm.csv', index=False, header=False)

data3 = data2.drop(['ias13', 'ias22', 'ias32'],axis=1)
data3

[[0.67825149 0.32754092 0.40875193 ... 0.30767788 0.26337883 0.23380704]
 [0.32754092 0.86454669 0.32960462 ... 0.25230993 0.20730735 0.17274049]
 [0.40875193 0.32960462 1.15027438 ... 0.36056001 0.38426903 0.28901083]
 ...
 [0.30767788 0.25230993 0.36056001 ... 0.55949533 0.22972656 0.22623235]
 [0.26337883 0.20730735 0.38426903 ... 0.22972656 0.70751841 0.21052014]
 [0.23380704 0.17274049 0.28901083 ... 0.22623235 0.21052014 0.34168191]]


ias1  ias2  ias3  ias4  ias5  ias6  ias7  ias8  ias9  ias10  ...  ias25  \
0       1     1     2     1     1     1     1     2     2      1  ...      1   
1       2     1     3     1     2     1     1     2     1      1  ...      1   
2       4     2     4     2     3     3     4     2     3      3  ...      2   
3       1     1     3     1     1     1     1     2     1      1  ...      1   
4       2     1     3     2     1     1     1     2     3      1  ...      1   
..    ...   ...   ...   ...   ...   ...   ...   ...   ...    ...  ...    ...   
202     1     1     3     2     2     1     1     2     1      1  ...      2   
203     1     1     4     1     1     1     1     3     1      1  ...      1   
204     3     2     4     3     2     3     2     4     4      2  ...      2   
205     3     1     5     1     1     3     4     3     2      2  ...      1   
206     1     1     1     1     2     1     3     4     4      3  ...      3   

     ias26  ias27  ias28  ias29  ias30  ias31  ias33  ias35  ias36  
0        1      3      1      1      1      1      1      1      1  
1        1      3      1      1      1      2      2      1      1  
2        3      3      2      2      3      3      2      1      3  
3        1      1      1      1      1      2      1      1      1  
4        1      3      1      1      1      2      1      3      1  
..     ...    ...    ...    ...    ...    ...    ...    ...    ...  
202      1      3      1      1      3      4      1      1      1  
203      1      2      1      1      1      2      1      2      1  
204      3      2      2      1      4      2      2      1      1  
205      2      4      3      1      1      4      1      1      1  
206      1      2      3      2      2      2      1      2      3  

[207 rows x 31 columns]

In [20]:
cov_mat2 = np.cov(data3.T)
cov_mat2

eigen_vals, eigen_vecs = np.linalg.eig(cov_mat2)
eigen_vals

array([9.39125543, 1.24515555, 1.10299324, 0.95304005, 0.77301975,
       0.63877591, 0.57708496, 0.53989026, 0.46848507, 0.44204512,
       0.41070427, 0.37201006, 0.36019535, 0.0453143 , 0.05559301,
       0.06549541, 0.32573639, 0.08833419, 0.10109319, 0.30962996,
       0.12344991, 0.13704314, 0.28016405, 0.16390667, 0.16615511,
       0.18382076, 0.19611993, 0.25722439, 0.24472739, 0.22869559,
       0.23002373])

In [21]:
pca = PCA(n_components=None)
f_data_pca = pca.fit_transform(data3)
pca.explained_variance_ratio_

array([0.4586205 , 0.06080698, 0.0538645 , 0.04654156, 0.0377503 ,
       0.03119452, 0.02818185, 0.02636546, 0.0228784 , 0.0215872 ,
       0.02005668, 0.01816705, 0.01759008, 0.01590729, 0.01512073,
       0.01368177, 0.01256151, 0.01195122, 0.01123317, 0.01116831,
       0.00957749, 0.00897686, 0.00811416, 0.00800436, 0.00669248,
       0.00602866, 0.00493687, 0.00431379, 0.00319846, 0.00271488,
       0.00221292])

In [22]:
pca_5 = PCA(n_components=5)
raq_pca2 = pca_5.fit_transform(data3)
pca_5.explained_variance_ratio_

array([0.4586205 , 0.06080698, 0.0538645 , 0.04654156, 0.0377503 ])