In [1]:
#Import Packages
import pandas as pd
import numpy as np
import sklearn.metrics as sk
from sklearn.metrics.pairwise import cosine_similarity

ModuleNotFoundError: No module named 'sklearn'

In [4]:
#Create the data as a DataFrame
data = [[1.5,1.7],[2,1.9], [1.6,1.8], [1.2,1.5],[1.5,1]]

df = pd.DataFrame(data, columns=['A1', 'A2'])

print(df)


    A1   A2
0  1.5  1.7
1  2.0  1.9
2  1.6  1.8
3  1.2  1.5
4  1.5  1.0


In [5]:
#Alternative way to manipulate data
x=np.array([
    [1.5,1.7], #x1 
    [2,1.9], #x2
    [1.6,1.8], #x3
    [1.2,1.5], #x4
    [1.5,1] #x5
])
print('Dataframe in numpy')
print(x)
print('')

y = np.array([[1.4,1.6]])

print('Query =', y)

Dataframe in numpy
[[1.5 1.7]
 [2.  1.9]
 [1.6 1.8]
 [1.2 1.5]
 [1.5 1. ]]

Query = [[1.4 1.6]]


In [6]:
#Pairwise function and Cosine Similarity
print("Cosine - Pairwise")
pair = 1 - sk.pairwise_distances(x, y, metric="cosine")
print(pair)
print('')
print("CosineSimilarity")
cosine_similarity(x,y)

Cosine - Pairwise
[[0.99999139]
 [0.99575226]
 [0.99996948]
 [0.99902823]
 [0.96536339]]

CosineSimilarity


array([[0.99999139],
       [0.99575226],
       [0.99996948],
       [0.99902823],
       [0.96536339]])

In [47]:
#Cleaned up and Ranked
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity

data = [[1.5, 1.7], [2, 1.9], [1.6, 1.8], [1.2, 1.5], [1.5, 1]]
df = pd.DataFrame(data, columns=['A1', 'A2'])

query_point = [[1.4, 1.6]]

cosine_similarities = cosine_similarity(df, query_point)

cosine_sim_df = pd.DataFrame(cosine_similarities, index=df.index, columns=['Cosine Similarity'])

ranked_points = cosine_sim_df.sort_values(by='Cosine Similarity', ascending=True) #This is wrong, its just not sorting correctly

print("Cosine Similarity Rankings:")
print(cosine_sim_df)
print('Closest to Furthest: 0,2,3,1,4' )

Cosine Similarity Rankings:
   Cosine Similarity
0           0.999991
1           0.995752
2           0.999969
3           0.999028
4           0.965363
Closest to Furthest: 0,2,3,1,4
